[
Description ("HPI Resource information"),
Provider("cmpi:HPI_LogicalDeviceProvider")
]

class HPI_LogicalDevice : CIM_LogicalDevice
{
	[Description ("Resource ID.") ]
		uint32 RID;
   
	[Description ("Domain ID.") ]
		uint32 DID;
   
	[Description ("Session ID.") ]
		uint32 SID;
		
	[Description ("ResourceRev.") ]
		uint8 ResourceRev;
		
	[Description ("SpecificVer.") ]
		uint8 SpecificVer;
    
	[Description ("DeviceSupport.") ]
		uint8 DeviceSupport;
    
	[Description ("ManufacturerId.") ]
		uint32 ManufacturerId;
    
	[Description ("ProductId.") ]
		uint16 ProductId;
    
	[Description ("FirmwareMajorRev.") ]
		uint8 FirmwareMajorRev;
    
	[Description ("FirmwareMinorRev.") ]
		uint8 FirmwareMinorRev;
    
	[Description ("AuxFirmwareRev.") ]
		uint8 AuxFirmwareRev;
    
	[MaxLen (16), Description ("Guid.") ]
		string Guid;
   
       [Description ("EntityPath") ]
		string EntityPath;
		
       [Description ("This definition defines the capabilities of a given"
		"resource. One resource may support any number of "
		"capabilities using the bit mask. Because each entry"
		"in an RPT will have the SAHPI_CAPABILITY_RESOURCE bit set, "
		"zero is not a valid value for the capability flag, and is "
		"thus used to indicate no RPT entry present in some function"
		" calls.") ]
		string Capabilities;
		
       [Description ("Indicates the hot swap capabilities of the resource") ]
		string HotSwapCapabilities; 
		    
       [Description ("Indicates the criticality that should be raised when "
		"the resource is not responding ") ]
		string ResourceSeverity; 
		
	[Description ("Indicates that the resource is not currently functional")]
		string ResourceFailed;      	

	[Description ("ResourceTag")]
		string ResourceTag;			  

};

