// Pegasus CIMOM registration mof

instance of PG_ProviderModule
{
   Name = "SimpleProcess_ProviderModule";
   Location = "SimpleProcess";				// library filename; i.e. lib<Location>.so
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   ProviderModuleName = "SimpleProcess_ProviderModule";	// same as PG_ProviderModule.Name
   Name = "SimpleProcess";				// provider name as specified in CMPIInstanceMI()
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName = "SimpleProcess_ProviderModule";	// same as PG_ProviderModule.Name
   ProviderName = "SimpleProcess";			// same as PG_Provider.Name
   CapabilityID = "1";
   ClassName = "SimpleProcess";				// classname from the mof
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 };				// 2 = Instance Provider
   SupportedProperties = NULL;				// NULL = all properties
   SupportedMethods = NULL;				// NULL = all methods
};

